---
output: pdf_document
---

#Abstract 

This report is about reproducing a simple regression analysis from Section 3.1 (pages 59-71), of *Chapter3. Linear Regression*, from the book "An Introduction to Statistical Learning" [(by James et al)](http://www-bcf.usc.edu/~gareth/ISL/)


# Introduction

The goal is to provide advice on how to improve sales of the particular product. The idea is to determine whether there is relationship between advertising expenditure and sales, and if so, we would like to know the strengh of this relationship and then we can instruct our client to adjust advertising budgets, thereby indirectly increasing sales.In other word, our goal is to develop an accurate model that can be used to prodect sales on the basis of the three media (TV, radio, newspaper) budgets.


# Data

The [Advertising data set](http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv) consists of Sales (in thousands of units) of a particular product in 200 different markets (n = 200), along with advertising budgets (in thousands of dollars) for the product in each of those markets for three different media: TV, Radio, and Newspaper.


# Methodology
We suppose that only one media from the data set, **TV**, has an association with **Sales**. Therefore, we use a simple linear model: 

$$ Sales = \beta_0 + \beta_1 \times TV $$

To estimate the coefficients we fit a regression model via the least squares criterion.




# Results



# Conclusions







```{r xtable, results = 'asis',warning=FALSE, message=FALSE, echo=FALSE, comment = FALSE}
load("../data/regression.RData")
library(xtable)
# table 1:
print(xtable(summary(reg)$coef, caption = "chart 1", type = "Latex"),comment = FALSE)

#table 2: 
f = summary(reg)$fstatistic
rse = summary(reg)$sigma
bb = summary(reg)
# R-square
r2 = bb$r.squared
c = c("Residual standard error","R2", "F-statistic")
v = c(rse,r2,f[1])
qq = data.frame(c,v)
colnames(qq) <- c("Quantity","Value")
print(xtable(qq, type = "html", caption = "chart 2"),comment = FALSE, include.rownames = FALSE)
```

[Regression of sales onto TV(https://github.com/MandyZhangxy/stat159-fall2016-hw02/blob/master/images/scatterplot-tv-sales.pdf)


![ This plot depicts minimizing the least squares criterion in simple linear regression. Each red dot in the plot corresponds to a data point in our training set. The blue line is the predicted output line obtained from our simple linear regression model. The vertical lines between the red dots and the blue line are the errors our prediction makes. These are the very same errors that we are minimizing via least squares (specifically, the it is the squares of these errors that we are minimizing). Thus, the observed blue line in the plot is the line that best minimizies these squared errors: it is the line that fits the closest to the data points in our training set.](https://github.com/jwilber/stat159-fall2016-hw02/blob/master/images/scatterplot-tv-sales.png?raw=true "Least Squares Simple Linear Regression")

